package com.articulo.service.entidad;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "articulo")
public class Articulo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String nombre;

    @DynamoDBAttribute
    private String unidadMedida;

    @DynamoDBAttribute
    private String clave;

    @DynamoDBAttribute
    private double precio;

    @Override
    public String toString() {
        return "{id: "+id+", nombre:"+nombre+", unidadMedida:"+unidadMedida+", clave:"+clave+", precio:"+precio+"}";
    }
}
